### PR TITLE
docs: refresh algolia index and re-deploy website when docs change

### PR DESCRIPTION
**Pull request by PatrickHeneise**
Add a GitHub Action to re-index /docs with Algolia and re-deploy the website with the latest changes on `main`

# Have you...

* [x] Discussed your change with a project contributor in an issue yet?
* [x] Added an explanation of what your changes do?
* [ ] Written new tests for your changes?
* [ ] Thought about which docs need updating?

### CODE REVIEW

**Comment by jgehrcke** [comment]
Thanks! Is this deploying to a staging environment (or something like that) or to opstrace.com/docs?

**Comment by PatrickHeneise** [comment]
Doesn't need deployment anywhere. It runs when there are changes in the `docs` folder on `main`

**Comment by jgehrcke** [comment]
> This refreshes opstrace.com/docs 

Okay, Yolo! :) :rocket: 

Would be cool to have a way to see how the result will look like (render) on the live site _before merging_. Is there?

**Comment by PatrickHeneise** [comment]
Little tricky, but could be possible. I'll open a ticket and investigate separately.

**Comment by triclambert** [comment]
> Would be cool to have a way to see how the result will look like (render) on the live site before merging. Is there?

There is a way to do this that involves a little bit of work.  Tl;dr: in a local clone of the website, you update it to point to your branch.  However, hopefully, GitHub rendering is good enough since we tried to match that very closely.

We'll probably come up with something better in the future.

**Review by triclambert — APPROVED** [review]

**Pull request merged**
