### PR TITLE
bump: cert-manager to 1.2.0

### PR DESCRIPTION
**Pull request by sreis**
We're seeing issues with cert-manager in CI again. Let's see if upgrading to the latest version helps address the issue.

### CODE REVIEW

**Comment by MatApple** [comment]
Congrats @sreis on generating this stuff 🎉 Still got a ways to go to make it easy, but I consider it a success that someone managed to do this without me 😂 💪 It's the first!

I rebased off main to trigger a new build - it looks good so I'd like to get it in!

**Comment by MatApple** [comment]
Both AWS and GCP are stuck waiting for the cert to become ready

**Comment by sreis** [comment]
> Congrats @sreis on generating this stuff 

Thanks! Although I couldn't get the key names not to be quoted (`"`).

> Both AWS and GCP are stuck waiting for the cert to become ready

Thank you for updating the PR. I'll have a look at the failures.

**Comment by MatApple** [comment]
Rebased again. Tests previously failed with CI instability

**Comment by MatApple** [comment]
@sreis fails with `[2021-02-25T03:50:23Z] 2021-02-25T03:50:23.042Z debug:     Waiting for Certificate ingress/https-cert to be ready`

**Comment by sreis** [comment]
Some of the cert-manager ClusterRoles required an update.

**Pull request merged**
