### PR TITLE
ui: simplier tenant name regex

### PR DESCRIPTION
**Pull request by terrcin**
Now that tenant names can't have a `-` in them the ui validation regex can be waaay simplier.

### CODE REVIEW

**Comment by terrcin** [comment]
Getting this happening: https://github.com/opstrace/opstrace/issues/944

Gonna wait a bit and then try again. This is unrelated to the work in this PR so I might just merge it despite the failure.

**Comment by MoSattler** [comment]
@terrcin may you also update the other tenant name regex for consistency?
https://github.com/opstrace/opstrace/blob/5825d3d97a8c36f78f93ba24fcf4dcd2ecbccf34/packages/config/src/clusterconfig.ts#L35

Maybe we're even able to have a SSOT for this, at least in the TS realm?

**Comment by jgehrcke** [comment]
> Maybe we're even able to have a SSOT for this

We absolutely should have one after all. For simple situations like this I want to at least have said that the source of truth does not need to exist in code, it may exist in docs/wiki etc.

I think the actual challenge here is that we're still in the process of making up our mind. And that we need to disambiguate the 'sane end goal' vs. the 'current state of affairs as of current limitations'.

Considerations:

* The fact that the hyphen is not supported today should be looked at as a temporary problem; let's add back support soon -- that is why I liked how @MoSattler simply removed it non-invasively via https://github.com/opstrace/opstrace/pull/998.
* After all there will need to be some length constraint on a tenant name, but I am not sure if it's 61. Did we test this? Maybe we should limit that to something lower, like 20.

**Comment by terrcin** [comment]
PR now nolonger needed as test failing has been identified and fixed in another PR which contained the work from this PR.

https://github.com/opstrace/opstrace/pull/1019

**Pull request closed without merging**
