### PR TITLE
chore: enable prometheus sharding

### LINKED ISSUE #214: Duplicate sample warnings in cortex ingester
**Describe the bug**

We are running multiple Prometheus scraping instances that are sending duplicate data to the cortex ingesters.

```
level=warn ts=2020-12-23T09:17:57.435754493Z caller=grpc_logging.go:38 method=/cortex.Ingester/Push duration=431.348µs err="rpc error: code = Code(400) desc = user=system: series={__name__=\"cluster_quantile:apiserver_request_duration_seconds:histogram_quantile\", component=\"apiserver\", endpoint=\"https\", group=\"coordination.k8s.io\", job=\"apiserver\", namespace=\"default\", prometheus=\"system-tenant/system-prometheus\", quantile=\"0.9\", resource=\"leases\", scope=\"namespace\", service=\"kubernetes\", verb=\"GET\", version=\"v1beta1\"}, timestamp=2020-12-23T09:17:56.932Z: duplicate sample for timestamp" msg="gRPC\n"
```

This increases the number of errors when ingesting data.

Screenshot from 2020-12-22 13-58-31

This is a graph of the ingesters sample failure rate when running Prometheus with the default configuration and then with 1 replica.

### PR DESCRIPTION
**Pull request by sreis**
From [Prometheus operator documentation](https://github.com/prometheus-operator/prometheus-operator/blob/02a5bac9610299372e9f77cbbe0c824ce636795b/Documentation/high-availability.md#prometheus)
> To run Prometheus in a highly available manner, two (or more) instances need to be running with the same configuration, that means they scrape the same targets, which in turn means they will have the same data in memory and on disk, which in turn means they are answering requests the same way. In reality this is not entirely true, as the scrape cycles can be slightly different, and therefore the recorded data can be slightly different. This means that single requests can differ slightly. What all of the above means for Prometheus is that there is a problem when a single Prometheus instance is not able to scrape the entire infrastructure anymore. This is where Prometheus' sharding feature comes into play. It divides the targets Prometheus scrapes into multiple groups, small enough for a single Prometheus instance to scrape. If possible functional sharding is recommended. What is meant by functional sharding is that all instances of Service A are being scraped by Prometheus A

For more info see this [issue](https://github.com/prometheus-operator/prometheus-operator/issues/3130#issuecomment-610506794) and the [PR](https://github.com/prometheus-operator/prometheus-operator/pull/3241).

Update docker images:
* Bump prometheus operator image to latest available [0.44.1](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.44.1)
* Bump prometheus kubernetes adapter image to [0.8.2](https://quay.io/repository/coreos/k8s-prometheus-adapter-amd64?tab=tags)
* Bump prometheus image to [2.23.0](https://quay.io/repository/prometheus/prometheus?tab=tags)

Prometheus docker image is now defined in the docker-images.json file.

Close #214

### CODE REVIEW

**Comment by sreis** [comment]
Turns out this will need a bit more work. I'll go ahead and set the number of replicas to 1 until this work is done.

**Comment by spahl** [comment]
TIL about prometheus sharding. Great feature. I much prefer this to having to duplicate and using the HA tracker in cortex.

**Comment by jgehrcke** [comment]
Let's push this forward :-) :heart:

**Comment by sreis** [comment]
Will work on it in the background.

**Pull request closed without merging**
