### PR TITLE
UI login: show "Access Denied" view only when appropriate, introduce generic login failure view, enhance robustness

### PR DESCRIPTION
**Pull request by jgehrcke**
See commit messages!

### CODE REVIEW

**Comment by jgehrcke** [comment]
Screenshot showing how a 403 response translates into the Access Denied error view:
Screenshot from 2021-08-13 11-20-59

**Comment by jgehrcke** [comment]
Screenshot showing how a 500 response translates into the new "Login failed" view:
Screenshot from 2021-08-12 17-13-10

**Comment by jgehrcke** [comment]
How much I missed that. Rather 'fast' CI feedback, no instabilities affected this PR. Can merge. :heart:

**Comment by jgehrcke** [comment]
In the CI build artifacts I confirmed that screenshots look good.

**Comment by jgehrcke** [comment]
Post-merge comments appreciated @MatApple :)

**Comment by MatApple** [comment]
LGTM! Nice clean up 💪

**Pull request merged**
