### PR TITLE
test-browser: migrate in the ring health test to help stabilise CI

### PR DESCRIPTION
**Pull request by terrcin**
White doing change I noticed that there was an `await` [missing](https://github.com/opstrace/opstrace/pull/1184/files#diff-0d2fcdddb14264ab274aba532f31800e276351ccf562e3e5ed4dcc72ac30fb73L608) from the original test-remote test which _may_ have been causing the problems on CI. The test should be under browser-test so I moved and corrected the problem.

### CODE REVIEW

**Comment by jgehrcke** [comment]
> White doing change I noticed that there was an await missing 

I wish for better tooling support on that one. For the record: https://github.com/eslint/eslint/issues/13567

**Comment by jgehrcke** [comment]
CC @MoSattler just so you know this is happening :)

**Comment by terrcin** [comment]
I've resolved the Unit Test failure. Getting this [CI Instability](https://github.com/opstrace/opstrace/issues/293) still.

**Comment by jgehrcke** [comment]
In `main-test-aws` in `test-browser` we got:
```
[2021-08-06T04:53:50Z]   1) [WebKit] › tests/pV0I9_clusterHealth.spec.ts:27:3 › cluster health all Cortext Ring Health tabs should render 
[2021-08-06T04:53:50Z]
[2021-08-06T04:53:50Z]     Timeout of 120000ms exceeded.
[2021-08-06T04:53:50Z]
[2021-08-06T04:53:50Z]     Pending operations:
[2021-08-06T04:53:50Z]       - page.waitForSelector at tests/pV0I9_clusterHealth.spec.ts:41:18
[2021-08-06T04:53:50Z]
[2021-08-06T04:53:50Z]     page.waitForSelector: Protocol error (Runtime.callFunctionOn): The page has been closed.
[2021-08-06T04:53:50Z]     =========================== logs ===========================
[2021-08-06T04:53:50Z]     waiting for selector "[data-test='ringTable/shards']" to be visible
[2021-08-06T04:53:50Z]     ============================================================
[2021-08-06T04:53:50Z]
[2021-08-06T04:53:50Z]       39 |     ]) {
[2021-08-06T04:53:50Z]       40 |       await page.click(`[data-test='ringHealth/tab/${tabName}']`);
[2021-08-06T04:53:50Z]     > 41 |       await page.waitForSelector(`[data-test='ringTable/shards']`);
[2021-08-06T04:53:50Z]          |                  ^
[2021-08-06T04:53:50Z]       42 |       expect(
[2021-08-06T04:53:50Z]       43 |         await page.waitForSelector(`[data-test='ringTable/shards/row/ACTIVE']`)
[2021-08-06T04:53:50Z]       44 |       ).toBeTruthy();
[2021-08-06T04:53:50Z]
[2021-08-06T04:53:50Z]         at /build/test/browser/tests/pV0I9_clusterHealth.spec.ts:41:18
[2021-08-06T04:53:50Z]         at WorkerRunner._runTestWithBeforeHooks (/build/test/browser/node_modules/@playwright/test/lib/test/workerRunner.js:390:7)
[2021-08-06T04:53:50Z]
[2021-08-06T04:53:50Z]     Retry #1 --------------------------------------------------------------------------------------
[2021-08-06T04:53:50Z]
[2021-08-06T04:53:50Z]     Timeout of 120000ms exceeded.
[2021-08-06T04:53:50Z]
[2021-08-06T04:53:50Z]     Pending operations:
[2021-08-06T04:53:50Z]       - page.waitForSelector at tests/pV0I9_clusterHealth.spec.ts:41:18
```
https://buildkite.com/opstrace/prs/builds/5375#ee3d142c-d15d-4f02-b0f6-dd98898dd4ca/2339-2357

I was excited to merge, but with that failure I don't feel comfortable doing so :).

**Comment by jgehrcke** [comment]
In the last `main-test-aws` run, still this error:
```
[2021-08-08T22:49:59Z]   1) [WebKit] › tests/rDsCp_clusterHealth.spec.ts:27:3 › cluster health all Cortext Ring Health tabs should render 
[2021-08-08T22:49:59Z]
[2021-08-08T22:49:59Z]     Timeout of 120000ms exceeded.
[2021-08-08T22:49:59Z]
[2021-08-08T22:49:59Z]     Pending operations:
[2021-08-08T22:49:59Z]       - page.waitForSelector at tests/rDsCp_clusterHealth.spec.ts:41:18
```
https://buildkite.com/opstrace/prs/builds/5415#f7baea2b-9619-4998-9837-9e272456a6be/2436-2454

**Comment by jgehrcke** [comment]
@terrcin  can you maybe give us an update about what your current understanding is about the ` Timeout of 120000ms exceeded.` errors here? Is the API not working as intended or the UI? Can @MoSattler help?

**Comment by terrcin** [comment]
Current CI failures are all only on Webkit, I assume that it's another browser incompatibility thing like the timestamp format fix I previously made. Will switch to a mac I have lying around to try and reproduce it.

**Comment by terrcin** [comment]
Upgrade tests failed, gonna merge anyways as all the tests related to my changes passed with flying colors. No idea why the upgrade tests failed, had a quick look but the word 'error' appears so many times.

**Comment by jgehrcke** [comment]
Thank you @terrcin :) Also thanks for adopting the `test-browser` commit message prefix!

**Comment by jgehrcke** [comment]
> Upgrade tests failed, gonna merge anyways as all the tests related to my changes passed with flying colors. No idea why the upgrade tests failed, had a quick look but the word 'error' appears so many times.

I recommend to patiently go through the individual phases of the CI run. You can then see that everything succeeded, except for the final `destroy` operation: https://buildkite.com/opstrace/prs/builds/5446#de3588c1-ef9d-4869-afc7-0b8b19f27dc1/7328-8254

Two instabilities affected that `destroy`. I have left the following corresponding comments:
* https://github.com/opstrace/opstrace/issues/47#issuecomment-895848408
* https://github.com/opstrace/opstrace/issues/976#issuecomment-895847372

**Pull request merged**
