### PR TITLE
Bump Tinify GHA to 1.3.1

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták gliptak@gmail.com

# Have you...

* [ ] Discussed your change with a project contributor in an issue yet?
* [ ] Added an explanation of what your changes do?
* [ ] Written new tests for your changes?
* [ ] Thought about which docs need updating?

### CODE REVIEW

**Comment by triclambert** [comment]
Hi @gliptak, thanks for the PR!  How did you find us and why did you select this change?  Just curious.

**Comment by gliptak** [comment]
@triclambert opstrace was referenced at https://www.thoughtworks.com/radar

When looking at projects, I like to check out their automation and improve them in some way

**Comment by triclambert** [comment]
Ok, well that's great—thanks. 

Do you mind resolving the DCO check with `git commit --amend --no-edit --signoff`?

**Comment by gliptak** [comment]
I will pull local and sign.

PS the DCO check prevents your contributors from using the Github GUI for quick updates ... I'm unclear what value DCO brings and it has negative impact

**Comment by triclambert** [comment]
Thanks so much.  Of course we know there are some limitations with the DCO, but we feel that it's the best of a series of bad options.  You can also type in the sign-off manually in the UI.

**Review by triclambert — APPROVED** [review]

**Pull request merged**
