### PR TITLE
feat(server): refactor env

### PR DESCRIPTION
**Pull request by MoSattler**
Small suggestion on cleaning up a little bit the env file.

# Have you...

* [ ] Discussed your change with a project contributor in an issue yet?
* [x] Added an explanation of what your changes do?
* [x] Written new tests for your changes?
* [x] Thought about which docs need updating?

### CODE REVIEW

**Comment by MatApple** [comment]
rebuilding in CI because playright failed to dowload

**Review by MatApple — APPROVED** [review]
Nice :-)

**Comment by jgehrcke** [comment]
> rebuilding in CI because playright failed to dowload

let's always note this in the corresponding ticket if it exists, I guess here: https://github.com/opstrace/opstrace/issues/696

**Comment by jgehrcke** [comment]
@MoSattler can you maybe prefix these commits an the PR with `ui: ` or with `app: `? :)

`feat(server)` is not really telling me in which part of our system the change happens. Also, `feat` is kind of only meaningful in the context of semantic versioning -- and in there, it would describe the addition/change of a user-facing feature.

**Comment by MatApple** [comment]
Yes great point @jgehrcke, thanks!

**Pull request merged**
