### PR TITLE
[wip] ui: trying to include the buildinfo file test-browser image

### PR DESCRIPTION
**Pull request by terrcin**

### CODE REVIEW

**Comment by jgehrcke** [comment]
I'd love to discuss commit messages here a bit, had been noticing something for a while :) I think we should have a prefix for changes in the UI web app / 'server', another one for changes in the UI/'client' (what's executed in the browser) and then a third one for changes in `test-browser`. For example:

- `ui: ` for what's executed in the browser
- `ui: app: ` for the backend/express thing
- `test-browser: `

When reading through commit messages to quickly grasp where changes happened then I think this will be really helpful, as compared to prefixing most of the commit messages you write with `ui: ` :)

**Comment by terrcin** [comment]
This is still failing on CI, frustratingly. FWIW it's works locally so it's todo with how (timing??) I'm getting the `buildinfo.json` file into the `test-browser` image.

The buildinfo.json that `test-browser` is using is different to that which the app is built with, I have test for that :-)

https://buildkite.com/opstrace/prs/builds/5514#8f53a060-c013-4e07-b5c0-71a6ce9fbc8a/5550-5621

```
[2021-08-12T07:06:27Z]   1) [Chromium] › tests/3AK3z_configuration.spec.ts:28:3 › configuration section opstrace should show the correct buildinfo from server
--
  | [2021-08-12T07:06:27Z]
  | [2021-08-12T07:06:27Z]     Error: expect(received).toBe(expected) // Object.is equality
  | [2021-08-12T07:06:27Z]
  | [2021-08-12T07:06:27Z]     Expected: "0413e40c-ci"
  | [2021-08-12T07:06:27Z]     Received: "0875381f-ci"
  | [2021-08-12T07:06:27Z]
  | [2021-08-12T07:06:27Z]       50 \| const expectInnerTextToBe = async (page: Page, value: string, key: string) => {
  | [2021-08-12T07:06:27Z]       51 \|   const hrefElement = await page.$(`[data-test='config/opstrace/${key}']`);
  | [2021-08-12T07:06:27Z]     > 52 \|   await expect(await hrefElement.innerText()).toBe(value);
  | [2021-08-12T07:06:27Z]          \|                                               ^
  | [2021-08-12T07:06:27Z]       53 \| };
  | [2021-08-12T07:06:27Z]       54 \|
```

Worth pointing out that I saw one test failure where the build times differed but the version sha didn't. :

https://buildkite.com/opstrace/prs/builds/5512#ea27fc60-f8d5-46dc-a725-c0ce37c0934f/5685-5756

```
[2021-08-12T01:37:16Z]   1) [Chromium] › tests/KHDlT_configuration.spec.ts:28:3 › configuration section opstrace should show the correct buildinfo from server
--
  | [2021-08-12T01:37:16Z]
  | [2021-08-12T01:37:16Z]     Error: expect(received).toBe(expected) // Object.is equality
  | [2021-08-12T01:37:16Z]
  | [2021-08-12T01:37:16Z]     Expected: "08/12/2021, 1:01:36 AM GMT+0"
  | [2021-08-12T01:37:16Z]     Received: "08/12/2021, 12:49:13 AM GMT+0"
  | [2021-08-12T01:37:16Z]
```

The make command `set-build-info-constants` which generates the buildinfo.json file is actually run by a [couple](https://github.com/opstrace/opstrace/blob/main/Makefile#L117) of [other](https://github.com/opstrace/opstrace/blob/main/Makefile#L241) [commands](https://github.com/opstrace/opstrace/blob/main/Makefile#L194) as a pre-requisit so I think it's quite concievable that that file is being generated more than once as part of the build process on CI.

**Comment by jgehrcke** [comment]
if the goal here was to check build info displayed in the UI against the 'expected' then of course it's almost a little philosophical to wonder what the reference should be. I'd argue that a good reference is `${OPSTRACE_PREBUILD_DIR}/buildinfo.json`, as written by https://github.com/opstrace/opstrace/blob/8a6275aff25615e439e9d51a0b02c85755bac8ac/ci/preamble.sh#L47. `${OPSTRACE_PREBUILD_DIR}/buildinfo.json` is on `/tmp on the host. Usually already mounted into the container. That is, it doesn't really make sense to bake it (the buildinfo file which is supposed to be the 'reference') into the image.

**Comment by jgehrcke** [comment]
Closing for now, let's pick up soon again.

**Pull request closed without merging**
