### PR TITLE
feat: integrate cortex-operator

### LINKED ISSUE #845: Integrate cortex-operator
After installing Opstrace and deploying the cortex-operator, this is the list of tasks we still need to tackle to integrate the cortex-operator in Opstrace.

#### Work on Opstrace CLI

- [x] remove `opstrace=owned` annotations from resources in cortex namespace; this needs to be done in the upgrade before updating the controller image; otherwise, it will delete these resources.
- [x] delete distributor, querier, and query-frontend deployment's; in Kubernetes, a deployments label selector field is immutable, and because the cortex-operator uses different label selectors, we need to delete the deployments and let the cortex-operator recreate them.

#### Work on Opstrace controller

- [x] install cortex-operator (CRD schema, create controller deployment etc.)
- [x] create cortex CRD resource with Opstrace default configuration

#### Work on Opstrace App/APIs
- [x] Set the runtime config in the cortex CRD resource instead of in a separate config map
  - [x] the controller needs to check if there's a previous runtime config and add it to the cortex crd spec 

#### cortex-operator

- [x] support image pull secrets 
- [x] handle ruler deployment
- [x] handle alertmanager deployment
- [x] configurable service account annotations (GCP requires the service account to have the `iam.gke.io/gcp-service-account` annotation)
- [ ] cut the first alpha release

Most likely, this work can be postponed to a later cortex-operator release. Meaning, for now, we will let the opstrace controller handle this work until the cortex-operator is capable of taking over.

- [ ] handle configs API deployment
  - [ ] configurable initContainers (configs needs to initialize the database)
- [ ] create Prometheus service monitor resources

### PR DESCRIPTION
**Pull request by sreis**
Close #845

### CODE REVIEW

**Comment by sreis** [comment]
I was expecting AWS test-remote to fail [test_submit_cortex_runtime_config](https://github.com/opstrace/opstrace/blob/sreis/integrate-cortex-operator/test/test-remote/test_ui.ts#L276:L276).

GCP build failed to bring up the Cortex `store-gateway` because it couldn't access the storage bucket. The `querier` was crash looping because it couldn't access the `store-gateway`. The Cortex `alertmanager` was crash looping because it couldn't access the storage bucket. The `ruler` was crash looping with the same reason. These errors were expected because the cortex service account doesn't [have the proper annotation](https://github.com/opstrace/opstrace/pull/869/files#diff-a0fcf929bb3b9b9f9e9594474c906f65970d10c5948ea768b23f9e204a2253daR224).

```
[2021-06-11T22:30:37Z] 2021-06-11T22:30:37.812Z [32minfo[39m: waiting for 3 Deployments
[2021-06-11T22:30:37Z] 2021-06-11T22:30:37.813Z [32minfo[39m: waiting for 0 DaemonSets
[2021-06-11T22:30:37Z] 2021-06-11T22:30:37.813Z [32minfo[39m: waiting for 1 StatefulSets
[2021-06-11T22:30:37Z] 2021-06-11T22:30:37.813Z [34mdebug[39m:     Waiting for 3 pods to be ready for StatefulSet cortex/store-gateway
```

store-gateway error:
```
2021-06-11 22:33:15	
level=error ts=2021-06-11T22:33:15.070630529Z caller=cortex.go:447 msg="module failed" module=store-gateway err="invalid service state: Failed, expected: Running, failure: initial blocks synchronization: The specified bucket does not exist"
```

Querier error:

```
2021-06-11 22:30:24	
level=error ts=2021-06-11T22:30:24.587778003Z caller=cortex.go:447 msg="module failed" module=querier err="failed to start querier, because it depends on module store-queryable, which has failed: invalid service state: Failed, expected: Running, failure: invalid service state: Failed, expected: Running, failure: unable to start blocks storage queryable subservices: not healthy, 0 terminated, 1 failed: [The specified bucket does not exist]"
```

Alertmanager error:
```
2021-06-11 22:25:27	
level=error ts=2021-06-11T22:25:27.532269532Z caller=cortex.go:447 msg="module failed" module=alertmanager err="invalid service state: Failed, expected: Running, failure: failed to list users with alertmanager configuration: The specified bucket does not exist"
```

Ruler error:
```
	
level=error ts=2021-06-11T22:30:35.298129652Z caller=cortex.go:447 msg="module failed" module=ruler err="failed to start ruler, because it depends on module store-queryable, which has failed: invalid service state: Failed, expected: Running, failure: invalid service state: Failed, expected: Running, failure: unable to start blocks storage queryable subservices: not healthy, 0 terminated, 1 failed: [The specified bucket does not exist]"
```

**Comment by sreis** [comment]
Rebased with main to trigger another round of tests.

Need to work on setting image pull secrets with the cortex-operator.

**Comment by sreis** [comment]
Rebased with main to trigger another round of tests.

**Comment by sreis** [comment]
Fixed merge conflicts and pushed to check which tests are breaking now.

**Comment by sreis** [comment]
The AWS tests failed with #981

**Comment by sreis** [comment]
Just hit an issue locally while testing the upgrade path. The cortex deployment is not working properly.  

One issue was that the query-frontend deployment was created by the cortex-operator and immediately deleted by the opstrace-controller. There are ways to handle this, for example, use a finalizer to prevent resources from being deleted. With a finalizer, the controller is called if one of the resources it manages is manually deleted. One downside is that it'll conflict with our current teardown method. During the teardown, the opstrace controller deletes all the resources this means the cortex-operator might be deleted before it has a chance to clean up the finalizers in the resources it manages that prevent them from being deleted. I need to think a bit more on this one.

After the upgrade I tried to fix things manually but now getting the following error in cortex queries: 

```
{"status":"error","errorType":"internal","error":"expanding series: empty ring"}
```

Prometheus is also having trouble pushing data

``
ts=2021-07-08T14:02:07.873Z caller=dedupe.go:112 component=remote level=warn remote_name=78b32e url=http://cortex-api.system-tenant.svc.cluster.local:8080/api/v1/push msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: DoBatch: InstancesCount <= 0"
```

**Comment by jgehrcke** [comment]
Just had an insightful discussion with @sreis about an architectural change regarding the Cortex runtime config. @sreis patiently answered my questions

Here is a summary of the architecture change that I missed:

Before https://github.com/opstrace/opstrace/pull/869 the Opstrace controller did set the Cortex `runtime_config -> file` config key to `/etc/cortex-runtime-cfg/runtime-config.yaml`. The UI backend did write directly to the config map mounted at `/etc/cortex-runtime-cfg/runtime-config.yaml`. That is, Cortex runtime config changes submitted through the UI did not propagate through the Opstrace controller. The controller did not need to run for UI-submitted Cortex runtime changes to apply.

Now, the `runtime_config -> file key is set to /etc/cortex/runtime-config.yaml` ([code(https://github.com/opstrace/cortex-operator/blob/3bfead5d9ba8263ac79c893533c963da4977e8e5/api/v1alpha1/cortex_webhook.go#L301-L303)]. Only the new Cortex operator writes directly to the config map mounted at that path (and guarantees to write a valid config). UI-submitted Cortex runtime updates are written to a config map that is not directly consumed by Cortex anymore, but by the Opstrace controller. The Opstrace controller responds to changes by updating the Cortex operator CRD. The Cortex operator responds to changes of that CRD: if the runtime configuration part of it changes, it validates the change. And if the change is valid it writes the new config map mounted at `/etc/cortex/runtime-config.yaml` in Cortex component containers. That is, both the following components needs to run for UI-submitted runtime config changes to apply: the Opstrace controller and the Cortex operator.

**Pull request merged**
