### PR TITLE
ci: add new gcp projects to shard ci builds over

### PR DESCRIPTION
**Pull request by triclambert**
See #293.

### CODE REVIEW

**Comment by triclambert** [comment]
Canceled build and merging to test this out.  (Tested locally with `ggg`.)

**Comment by triclambert** [comment]
See also #1344.

**Comment by triclambert** [comment]
Triggered manual build on main here:  https://buildkite.com/opstrace/scheduled-main-builds/builds/3000

**Comment by jgehrcke** [comment]
> Local test also eventually failed on ci-shard-ggg.

what was the conclusion here?

**Comment by sreis** [comment]
For the record, things seem to be functional now on [project ci-shard-ggg](https://buildkite.com/opstrace/scheduled-main-builds/builds/3005#d2c20f21-fb71-4023-8ddb-5d367dcc70e6/315-316)  :man_shrugging:

**Pull request merged**
