### PR TITLE
fix(test-remote): dockerfile for mac

### PR DESCRIPTION
**Pull request by MoSattler**
See [this](https://opstrace-community.slack.com/archives/C01KZS8JRNC/p1622821569060600?thread_ts=1622818862.054700&cid=C01KZS8JRNC) and following messages.

# Have you...

* [ ] Discussed your change with a project contributor in an issue yet?
* [ ] Added an explanation of what your changes do?
* [ ] Written new tests for your changes?
* [ ] Thought about which docs need updating?

### CODE REVIEW

**Review by spahl — APPROVED** [review]

**Comment by triclambert** [comment]
Doing a quick test of this branch in the background on my M1...  test failed.

```bash
~/workspace/opstrace mosattler/mac-dockerfile ?3           3m 29s 09:30:20
> make rebuild-testrunner-container-images
--------------------------------------------------------------
OPSTRACE_CLUSTER_NAME is democluster
OPSTRACE_BUILD_DIR is /Users/clambert/workspace/opstrace
OPSTRACE_CLOUD_PROVIDER is aws
DOCKER_GID_HOST is
OPSTRACE_KUBE_CONFIG_HOST is /Users/clambert/.kube
CHECKOUT_VERSION_STRING is 0ddc788b3-dev
KERNEL_NAME is darwin
--------------------------------------------------------------
--- building testrunner container image
docker build . --rm --force-rm \
	-t opstrace/test-remote:0ddc788b3-dev \
	-f ./test/test-remote/nodejs-testrunner.Dockerfile
[+] Building 719.3s (18/18) FINISHED
 => [internal] load build definition from nodejs-testrunner.Dockerfile        0.1s
 => => transferring dockerfile: 104B                                          0.0s
 => [internal] load .dockerignore                                             0.1s
 => => transferring context: 83B                                              0.0s
 => [internal] load metadata for docker.io/library/node:14-buster             1.6s
 => [auth] library/node:pull token for registry-1.docker.io                   0.0s
 => [internal] load build context                                             0.1s
 => => transferring context: 1.26MB                                           0.1s
 => [ 1/12] FROM docker.io/library/node:14-buster@sha256:d1d71f63a8b92fa73d8  0.0s
 => CACHED [ 2/12] RUN apt-get update && apt-get install -y -q --no-install-  0.0s
 => CACHED [ 3/12] RUN curl -sSL -O https://storage.googleapis.com/kubernete  0.0s
 => CACHED [ 4/12] RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x  0.0s
 => CACHED [ 5/12] COPY package.json tsconfig.json /build/                    0.0s
 => CACHED [ 6/12] COPY yarn.lock test/test-remote/package.json test/test-re  0.0s
 => [ 7/12] COPY lib/kubernetes/ /build/lib/kubernetes/                       0.1s
 => [ 8/12] COPY lib/utils/ /build/lib/utils/                                 0.1s
 => [ 9/12] COPY packages/buildinfo/ /build/packages/buildinfo/               0.0s
 => [10/12] WORKDIR /build/test/test-remote                                   0.0s
 => [11/12] RUN cat package.json tsconfig.json &&     echo /build: && ls -  432.9s
 => [12/12] RUN playwright -h &&     cd /build/test/test-remote &&     yar  263.3s
 => exporting to image                                                       21.0s
 => => exporting layers                                                      21.0s
 => => writing image sha256:5e20343bb90261964af16288035886e882b4f045afaf66c9  0.0s
 => => naming to docker.io/opstrace/test-remote:0ddc788b3-dev                 0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
docker pull opstrace/systemlog-fluentd:fe6d0d84-dev
fe6d0d84-dev: Pulling from opstrace/systemlog-fluentd
Digest: sha256:ed86ccc8044a6909ea48f032af635e5dc81fd0005fd932eb46caa28230f2622f
Status: Image is up to date for opstrace/systemlog-fluentd:fe6d0d84-dev
docker.io/opstrace/systemlog-fluentd:fe6d0d84-dev
docker pull prom/prometheus:v2.21.0
v2.21.0: Pulling from prom/prometheus
fd44016e3d3e: Pull complete
71baab61fa60: Pull complete
342afda08b4f: Pull complete
30c70a4df803: Pull complete
f66c223688e8: Pull complete
9327c212f85c: Pull complete
4f40acf8e585: Pull complete
67d9943de656: Pull complete
b9c749b1af90: Pull complete
9723d8eb5323: Pull complete
eb9cca4316d4: Pull complete
c39d6cc6c84e: Pull complete
Digest: sha256:d43417c260e516508eed1f1d59c10c49d96bbea93eafb4955b0df3aea5908971
Status: Downloaded newer image for prom/prometheus:v2.21.0
docker.io/prom/prometheus:v2.21.0
docker pull gcr.io/datadoghq/agent:7
7: Pulling from datadoghq/agent
2ded7c9b0858: Pull complete
Digest: sha256:421792d71c01542c3427b253dd9fae43ccdcf8e766d8f695dd83a20c372d9710
Status: Downloaded newer image for gcr.io/datadoghq/agent:7
gcr.io/datadoghq/agent:7

~/workspace/opstrace mosattler/mac-dockerfile ?3              INT 10:01:08
> make test-remote
--------------------------------------------------------------
OPSTRACE_CLUSTER_NAME is democluster
OPSTRACE_BUILD_DIR is /Users/clambert/workspace/opstrace
OPSTRACE_CLOUD_PROVIDER is aws
DOCKER_GID_HOST is
OPSTRACE_KUBE_CONFIG_HOST is /Users/clambert/.kube
CHECKOUT_VERSION_STRING is 0ddc788b3-dev
KERNEL_NAME is darwin
--------------------------------------------------------------
Unable to find image 'mvance/unbound:1.12.0' locally
1.12.0: Pulling from mvance/unbound
6c33745f49b4: Pulling fs layer
0ff467e2b507: Pulling fs layer
4737e5309c70: Pulling fs layer
5f837618ee1a: Pulling fs layer
a861b268b037: Pulling fs layer
5a8cd8dbb826: Pulling fs layer
da3d9b44f421: Pulling fs layer
1a45f80fa340: Pulling fs layer
5e73ff3ece80: Pulling fs layer
5f837618ee1a: Waiting
a861b268b037: Waiting
da3d9b44f421: Waiting
1a45f80fa340: Waiting
5e73ff3ece80: Waiting
0ff467e2b507: Verifying Checksum
0ff467e2b507: Download complete
5f837618ee1a: Verifying Checksum
5f837618ee1a: Download complete
a861b268b037: Verifying Checksum
a861b268b037: Download complete
5a8cd8dbb826: Verifying Checksum
5a8cd8dbb826: Download complete
da3d9b44f421: Verifying Checksum
da3d9b44f421: Download complete
1a45f80fa340: Verifying Checksum
1a45f80fa340: Download complete
5e73ff3ece80: Verifying Checksum
5e73ff3ece80: Download complete
6c33745f49b4: Download complete
6c33745f49b4: Pull complete
0ff467e2b507: Pull complete
4737e5309c70: Verifying Checksum
4737e5309c70: Download complete
4737e5309c70: Pull complete
5f837618ee1a: Pull complete
a861b268b037: Pull complete
5a8cd8dbb826: Pull complete
da3d9b44f421: Pull complete
1a45f80fa340: Pull complete
5e73ff3ece80: Pull complete
Digest: sha256:6b1b50098756b9b7646123873ffe7bb75e22acd983e34904adb9b762b81664c2
Status: Downloaded newer image for mvance/unbound:1.12.0
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker run --tty --interactive --rm \
	-v /Users/clambert/.kube:/kubeconfig:ro \
	-u 501: \
	-v /etc/passwd:/etc/passwd \
	-e KUBECONFIG=/kubeconfig/config \
	-e AWS_ACCESS_KEY_ID \
	-e AWS_SECRET_ACCESS_KEY \
	--dns 172.17.0.2 \
	opstrace/test-remote:0ddc788b3-dev \
	kubectl cluster-info
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server 968DECBC1F7B178B3BCFD315F6846DF8.gr7.us-west-2.eks.amazonaws.com was refused - did you specify the right host or port?
make: *** [Makefile:555: kubectl-cluster-info] Error 1

~/workspace/opstrace mosattler/mac-dockerfile ?3   30s kube democluster 10:01:40
> kubectl cluster-info
Kubernetes control plane is running at https://968DECBC1F7B178B3BCFD315F6846DF8.gr7.us-west-2.eks.amazonaws.com
CoreDNS is running at https://968DECBC1F7B178B3BCFD315F6846DF8.gr7.us-west-2.eks.amazonaws.com/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

~/workspace/opstrace mosattler/mac-dockerfile ?3  kube democluster 10:03:56
> kubectl get pods -n cortex | head
NAME                              READY   STATUS    RESTARTS   AGE
alertmanager-5cf6dc854b-nmcm2     1/1     Running   0          2d2h
alertmanager-5cf6dc854b-rrvr9     1/1     Running   0          2d2h
alertmanager-5cf6dc854b-zf5lm     1/1     Running   0          2d2h
compactor-0                       1/1     Running   0          2d2h
compactor-1                       1/1     Running   0          2d2h
compactor-2                       1/1     Running   0          2d2h
configs-78cb86c5cf-8w7d4          1/1     Running   0          2d2h
distributor-65c778f89-75mk6       1/1     Running   0          2d2h
distributor-65c778f89-7zjhg       1/1     Running   0          2d2h

~/workspace/opstrace mosattler/mac-dockerfile ?3                  10:04:45
> env | grep OPSTRACE
OPSTRACE_CLUSTER_NAME=democluster
OPSTRACE_CLOUD_PROVIDER=aws
```

**Comment by MoSattler** [comment]
@triclambert looks like you're using buildkit, right? 

I still am using "old" docker, and at least the build works fine - but the remote test still fails.

**Comment by triclambert** [comment]
Yes, I'm up-to-date.  Just wanted to offer a test environment.  :)

**Comment by jgehrcke** [comment]
How do we move this one forward?

> Doing a quick test of this branch in the background on my M1... test failed.

Based on this comment it doesn't look like we want to merge this as-is or do we? If someone has a strong opinion, please share!

**Comment by triclambert** [comment]
The build works for me, so assuming it works for Mo as well, we can merge this now.

**Comment by PatrickHeneise** [comment]
I had a similar issue and Docker added "cross platform builds" with builders:

`docker buildx build .--platform linux/amd64`

https://blog.jaimyn.dev/how-to-build-multi-architecture-docker-images-on-an-m1-mac/

**Comment by triclambert** [comment]
Thanks, @PatrickHeneise, Mo made this change so I think we're good to go.

**Pull request merged**
