### PR TITLE
feat: add image processing and upload workflows

### PR DESCRIPTION
**Pull request by PatrickHeneise**
This adds two GitHub Action workflows to the repo:

1. Image Processing: new images in PRs will automatically be optimized for web usage
2. Asset upload: docs/assets will be uploaded to S3 to be used on the website

# Have you...

* [x] Discussed your change with a project contributor in an issue yet?
* [x] Added an explanation of what your changes do?
* [x] Thought about which docs need updating?

### CODE REVIEW

**Review by triclambert — APPROVED** [review]
Looks good.  How do we test?

**Comment by nickbp** [comment]
FYI I'm seeing this error in PR CI which looked related to this PR:
`Error: Unsupported event pull_request_target (currently supported events include push, pull_request)`

Example failure: https://github.com/opstrace/opstrace/pull/490/checks?check_run_id=2126379363

**Comment by jgehrcke** [comment]
> How do we test?

Ideally before merging :-)

**Comment by triclambert** [comment]
Forgive me as I missed this yesterday.  Thanks to @jgehrcke for the direct ping to follow up.  Rather than reverting, I fixed it forward in #501.  PTAL and let me know if anything is missing.

**Comment by jgehrcke** [comment]
Thanks, Chris!

**Comment by PatrickHeneise** [comment]
The issue with Actions is that they don't work until merged to `main`. I did of course test all of this in a private repo before, but things are different working with public repos and forks.

When using `pull_request`, a PR from a fork will _not_ have access to the `TINIFY_API_KEY` and therefore will fail, that's why GitHub introduced `pull_request_target`. You can read more about it here: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/.

I'm not sure why you get an error about that event though.

**Comment by PatrickHeneise** [comment]
Just figured out this is an error thrown by the [tinify action](https://github.com/namoscato/action-tinify/blob/82e1bbdcbeaedbd7ac487b76e369fa01a03a47dc/src/git.ts#L119), not from GitHub (thanks @steffen). Will see how I can get this to work with `pull_request_target`.

**Pull request merged**
