### PR TITLE
ci: gcp: try using ci-shard-aaa project (wip)

### PR DESCRIPTION
**Pull request by jgehrcke**

### CODE REVIEW

**Comment by jgehrcke** [comment]
> [2020-12-08T12:49:18Z] ApiError: Cloud DNS API has not been used in project 540196616614 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/dns.googleapis.com/overview?project=540196616614 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

Tackling that.

**Comment by jgehrcke** [comment]
```
[2020-12-08T14:44:00Z] 2020-12-08T14:44:00.317Z error: JSON representation of err: {
[2020-12-08T14:44:00Z]   "code": 403,
[2020-12-08T14:44:00Z]   "errors": [
[2020-12-08T14:44:00Z]     {
[2020-12-08T14:44:00Z]       "message": "Compute Engine API has not been used in project 540196616614 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=540196616614 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
[2020-12-08T14:44:00Z]       "domain": "usageLimits",
[2020-12-08T14:44:00Z]       "reason": "accessNotConfigured",
[2020-12-08T14:44:00Z]       "extendedHelp": "https://console.developers.google.com"
[2020-12-08T14:44:00Z]     }
[2020-12-08T14:44:00Z]   ],
```
Now tackling that.

**Comment by jgehrcke** [comment]
```
[2020-12-08T14:53:27Z] 2020-12-08T14:53:27.281Z error: error during cluster creation (attempt 3):
[2020-12-08T14:53:27Z] Error: 7 PERMISSION_DENIED: Kubernetes Engine API has not been used in project 540196616614 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=54<snip6614 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
[2020-12-08T14:53:27Z]     at Object.callErrorFromStatus (/snapshot/build/node_modules/@grpc/grpc-js/src/call.ts:81:24)
[2020-12-08T14:53:27Z]     at Object.onReceiveStatus (/snapshot/build/node_modules/@grpc/grpc-js/src/client.ts:334:36)
[2020-12-08T14:53:27Z]     at Object.onReceiveStatus (/snapshot/build/node_modules/@grpc/grpc-js/src/client-interceptors.ts:434:34)
[2020-12-08T14:53:27Z]     at Object.onReceiveStatus (/snapshot/build/node_modules/@grpc/grpc-js/src/client-interceptors.ts:397:48)
[2020-12-08T14:53:27Z]     at /snapshot/build/node_modules/@grpc/grpc-js/src/call-stream.ts:237:24
[2020-12-08T14:53:27Z]     at processTicksAndRejections (internal/process/task_queues.js:79:11) {
[2020-12-08T14:53:27Z]   code: 7,
[2020-12-08T14:53:27Z]   details: 'Kubernetes Engine API has not been used in project 54<snip>14 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/container.googleapis.com/overview?project=54<snip4 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.',
[2020-12-08T14:53:27Z]   metadata: [Metadata],
[2020-12-08T14:53:27Z]   note: 'Exception occurred in retry method that was not classified as transient'
[2020-12-08T14:53:27Z] }
```

**Comment by jgehrcke** [comment]
```
[2020-12-08T15:16:39Z]       "error": {
[2020-12-08T15:16:39Z]         "code": 403,
[2020-12-08T15:16:39Z]         "message": "Cloud SQL Admin API has not been used in project 5<snip>4 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=5<snip>4 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
[2020-12-08T15:16:39Z]         "errors": [
[2020-12-08T15:16:39Z]           {
[2020-12-08T15:16:39Z]             "message": "Cloud SQL Admin API has not been used in project 5<snip>4 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=5<snip>4 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
[2020-12-08T15:16:39Z]             "domain": "usageLimits",
[2020-12-08T15:16:39Z]             "reason": "accessNotConfigured",
[2020-12-08T15:16:39Z]             "extendedHelp": "https://console.developers.google.com"
[2020-12-08T15:16:39Z]           }
[2020-12-08T15:16:39Z]         ],
[2020-12-08T15:16:39Z]         "status": "PERMISSION_DENIED"
[2020-12-08T15:16:39Z]       }
[2020-12-08T15:16:39Z]     },
```

**Comment by jgehrcke** [comment]
```
[2020-12-08T16:24:55Z] 2020-12-08T16:24:55.431Z info: GKECluster is PROVISIONING
[2020-12-08T16:24:55Z] 2020-12-08T16:24:55.654Z error: failed creating service peering for cloudSQL and cluster vpc: % Service Networking API has not been used in project 54<snip>4 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/servicenetworking.googleapis.com/overview?project=5<snip>4 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.: Error: Service Networking API has not been used in project 5<snip>4 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/servicenetworking.googleapis.com/overview?project=540196616614 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
[2020-12-08T16:24:55Z]     at Gaxios._request (/snapshot/build/node_modules/gaxios/src/gaxios.ts:117:15)
[2020-12-08T16:24:55Z]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jgehrcke** [comment]
```
[2020-12-08T17:26:03Z] 2020-12-08T17:26:03.945Z error: failed creating service peering for cloudSQL and cluster vpc: % The caller does not have permission: Error: The caller does not have permission
[2020-12-08T17:26:03Z]     at Gaxios._request (/snapshot/build/node_modules/gaxios/src/gaxios.ts:117:15)
[2020-12-08T17:26:03Z]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-12-08T17:26:03Z]     at JWT.requestAsync (/snapshot/build/node_modules/google-auth-library/build/src/auth/oauth2client.js:343:18)
[2020-12-08T17:26:03Z]     at peerVpcs (/snapshot/build/node_modules/@opstrace/gcp/build/cloudSQL.js:0)
```

**Comment by jgehrcke** [comment]
```
[2020-12-08T18:29:35Z]     "data": {
[2020-12-08T18:29:35Z]       "error": {
[2020-12-08T18:29:35Z]         "code": 403,
[2020-12-08T18:29:35Z]         "message": "Cloud Resource Manager API has not been used in project 540196616614 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=5<snip>4 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
[2020-12-08T18:29:35Z]         "errors": [
[2020-12-08T18:29:35Z]           {
[2020-12-08T18:29:35Z]             "message": "Cloud Resource Manager API has not been used in project 540196616614 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=5<snip>4 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
[2020-12-08T18:29:35Z]             "domain": "usageLimits",
[2020-12-08T18:29:35Z]             "reason": "accessNotConfigured",
[2020-12-08T18:29:35Z]             "extendedHelp": "https://console.developers.google.com"
[2020-12-08T18:29:35Z]           }
[2020-12-08T18:29:35Z]         ],
[2020-12-08T18:29:35Z]         "status": "PERMISSION_DENIED"
[2020-12-08T18:29:35Z]       }
[2020-12-08T18:29:35Z]     },
```

**Comment by jgehrcke** [comment]
```
[2020-12-08T18:42:14Z]   "response": {
[2020-12-08T18:42:14Z]     "config": {
[2020-12-08T18:42:14Z]       "url": "https://cloudresourcemanager.googleapis.com/v1/projects/ci-shard-aaa:setIamPolicy",
[2020-12-08T18:42:14Z]       "method": "POST",
...
[2020-12-08T18:42:14Z]     },
[2020-12-08T18:42:14Z]     "data": {
[2020-12-08T18:42:14Z]       "error": {
[2020-12-08T18:42:14Z]         "code": 403,
[2020-12-08T18:42:14Z]         "message": "Policy update access denied.",
[2020-12-08T18:42:14Z]         "errors": [
[2020-12-08T18:42:14Z]           {
[2020-12-08T18:42:14Z]             "message": "Policy update access denied.",
[2020-12-08T18:42:14Z]             "domain": "global",
[2020-12-08T18:42:14Z]             "reason": "forbidden"
[2020-12-08T18:42:14Z]           }
[2020-12-08T18:42:14Z]         ],
[2020-12-08T18:42:14Z]         "status": "PERMISSION_DENIED"
[2020-12-08T18:42:14Z]       }
[2020-12-08T18:42:14Z]     },
```

**Comment by jgehrcke** [comment]
```
[2020-12-08T18:48:15Z] 2020-12-08T18:48:15.954Z [31merror[39m: caught error and will retry later: {
[2020-12-08T18:48:15Z]   "response": {
[2020-12-08T18:48:15Z]     "config": {
[2020-12-08T18:48:15Z]       "url": "https://iam.googleapis.com/v1/projects/ci-shard-aaa/serviceAccounts/bk-3203-516-g-cert-manager@ci-shard-aaa.iam.gserviceaccount.com:setIamPolicy",
[2020-12-08T18:48:15Z]       "method": "POST",
[2020-12-08T18:48:15Z]       "userAgentDirectives": [

...

[2020-12-08T18:48:15Z]     "data": {
[2020-12-08T18:48:15Z]       "error": {
[2020-12-08T18:48:15Z]         "code": 403,
[2020-12-08T18:48:15Z]         "message": "Permission iam.serviceAccounts.setIamPolicy is required to perform this operation on service account projects/ci-shard-aaa/serviceAccounts/bk-3203-516-g-cert-manager@ci-shard-aaa.iam.gserviceaccount.com.",
[2020-12-08T18:48:15Z]         "errors": [
[2020-12-08T18:48:15Z]           {
[2020-12-08T18:48:15Z]             "message": "Permission iam.serviceAccounts.setIamPolicy is required to perform this operation on service account projects/ci-shard-aaa/serviceAccounts/bk-3203-516-g-cert-manager@ci-shard-aaa.iam.gserviceaccount.com.",
[2020-12-08T18:48:15Z]             "domain": "global",
[2020-12-08T18:48:15Z]             "reason": "forbidden"
[2020-12-08T18:48:15Z]           }
[2020-12-08T18:48:15Z]         ],
```

**Comment by jgehrcke** [comment]
manual build: https://buildkite.com/opstrace/prs/builds/3213

**Comment by jgehrcke** [comment]
last problem:
```
[2020-12-08T20:13:40Z]     "message": "configmaps is forbidden: User \"buildkite@vast-pad-2snip18.iam.gserviceaccount.com\" cannot create resource \"configmaps\" in API group \"\" in the namespace \"default\": requires one of [\"container.configMaps.create\"] permission(s).",
```

**Comment by jgehrcke** [comment]
```
[2020-12-09T12:46:22Z] 2020-12-09T12:46:22.868Z info: api err during createResource for opstrace-controller-clusteradmin-binding(ns: default): {"response":{"statusCode":403,"body":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"clusterrolebindings.rbac.authorization.k8s.io is forbidden: User \"ci-shard-aaa-svc-acc@ci-shard-aaa.iam.gserviceaccount.com\" cannot create resource \"clusterrolebindings\" in API group \"rbac.authorization.k8s.io\" at the cluster scope: requires one of [\"container.clusterRoleBindings.create\"] permission(s).","reason":"Forbidden","details":{"group":"rbac.authorization.k8s.io","kind":"clusterrolebindings"},"code":403},"headers":{"audit-id":"7bd3<snip>01","cache-control":"no-cache, private","content-type":"application/json","x-content-type-options":"nosniff","date":"Wed, 09 Dec 2020 12:46:22 GMT","content-length":"503","connection":"close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"34.94.174.215","port":443,"hostname":"34.94.174.215","hash":null,"search":null,"query":null,"pathname":"/apis/rbac.authorization.k8s.io/v1/clusterrolebindings","path":"/apis/rbac.authorization.k8s.io/v1/clusterrolebindings","href":"https://34.94.174.215/apis/rbac.authorization.k8s.io/v1/clusterrolebindings"},"method":"POST","headers":{"Accept":"application/json","Authorization":"Bearer ya<snip>oJP0","content-type":"application/json","content-length":364}}},"body":{"apiVersion":"v1","kind":"Status","metadata":{}},"statusCode":403,"name":"HttpError"}
```

**Comment by jgehrcke** [comment]
current build here: https://buildkite.com/opstrace/prs/builds/3226

**Comment by jgehrcke** [comment]
Loki ingester won't start:
Screenshot from 2020-12-09 15-42-09

**Comment by jgehrcke** [comment]
```
$ gcloud container clusters get-credentials bk-3226-760-g --zone us-west2-a --project <snip>
$ export OPSTRACE_CLUSTER_NAME=bk-3226-760-g
$ kubectl get all --namespace=loki 2>/dev/null | awk '{print $1}' | \
>     grep 'pod/' | while read PNAME; do echo "get logs for $PNAME" | \
>     tee /dev/stderr ; kubectl logs $PNAME --namespace=loki --all-containers=true; done \
>     > clusterlogs_loki-${OPSTRACE_CLUSTER_NAME}.log
get logs for pod/compactor-bc4bc45c-pwhwz
get logs for pod/distributor-6df5bdd64f-254kv
get logs for pod/distributor-6df5bdd64f-fg4r5
get logs for pod/distributor-6df5bdd64f-k4qzt
get logs for pod/ingester-0
get logs for pod/ingester-1
get logs for pod/ingester-2
get logs for pod/memcached-0
get logs for pod/memcached-1
get logs for pod/memcached-index-queries-0
get logs for pod/memcached-index-queries-1
get logs for pod/memcached-index-writes-0
get logs for pod/memcached-index-writes-1
get logs for pod/querier-0
get logs for pod/querier-1
get logs for pod/querier-2
```

**Comment by jgehrcke** [comment]
log tail end of a loki ingester instance:
```
level=warn ts=2020-12-09T15:10:20.993824719Z caller=grpc_logging.go:55 method=/logproto.Ingester/TransferChunks duration=1.000692395s err="no series" msg="gRPC\n"
level=info ts=2020-12-09T15:10:21.99405811Z caller=lifecycler.go:394 msg="auto-joining cluster after timeout" ring=ingester
level=info ts=2020-12-09T15:10:22.994901166Z caller=lifecycler.go:403 msg="observing tokens before going ACTIVE" ring=ingester
level=info ts=2020-12-09T15:10:50.642244891Z caller=table_manager.go:171 msg="uploading tables"
level=warn ts=2020-12-09T15:10:52.621303928Z caller=lifecycler.go:232 msg="found an existing instance(s) with a problem in the ring, this instance cannot become ready until this problem is resolved. The /ring http endpoint on the distributor (or single binary) provides visibility into the ring." ring=ingester err="instance ingester-1 in state JOINING"
level=info ts=2020-12-09T15:10:52.995405135Z caller=lifecycler.go:422 msg="token verification successful" ring=ingester
level=info ts=2020-12-09T15:10:52.995456918Z caller=lifecycler.go:743 msg="changing instance state from" old_state=JOINING new_state=ACTIVE ring=ingester
level=warn ts=2020-12-09T15:11:00.224484634Z caller=lifecycler.go:232 msg="found an existing instance(s) with a problem in the ring, this instance cannot become ready until this problem is resolved. The /ring http endpoint on the distributor (or single binary) provides visibility into the ring." ring=ingester err="instance ingester-1 in state JOINING"
level=info ts=2020-12-09T15:11:00.249009344Z caller=signals.go:55 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
level=info ts=2020-12-09T15:11:00.249254673Z caller=lifecycler.go:444 msg="lifecycler loop() exited gracefully" ring=ingester
level=info ts=2020-12-09T15:11:00.249284213Z caller=lifecycler.go:743 msg="changing instance state from" old_state=ACTIVE new_state=LEAVING ring=ingester
level=info ts=2020-12-09T15:11:00.24963855Z caller=transfer.go:214 msg="sending chunks" to_ingester=10.220.0.28:9095
level=error ts=2020-12-09T15:11:01.254544122Z caller=transfer.go:200 msg="transfer failed" err="CloseAndRecv: rpc error: code = Unknown desc = no series"
level=error ts=2020-12-09T15:11:01.447133067Z caller=transfer.go:200 msg="transfer failed" err="cannot find ingester to transfer chunks to: no pending ingesters"
level=error ts=2020-12-09T15:11:01.839977088Z caller=transfer.go:200 msg="transfer failed" err="cannot find ingester to transfer chunks to: no pending ingesters"
level=error ts=2020-12-09T15:11:02.335835842Z caller=transfer.go:200 msg="transfer failed" err="cannot find ingester to transfer chunks to: no pending ingesters"
level=error ts=2020-12-09T15:11:03.315779438Z caller=transfer.go:200 msg="transfer failed" err="cannot find ingester to transfer chunks to: no pending ingesters"
level=info ts=2020-12-09T15:11:06.095205739Z caller=transfer.go:214 msg="sending chunks" to_ingester=10.220.0.28:9095
level=error ts=2020-12-09T15:11:07.098404946Z caller=transfer.go:200 msg="transfer failed" err="CloseAndRecv: rpc error: code = Unknown desc = no series"
level=error ts=2020-12-09T15:11:11.37914844Z caller=transfer.go:200 msg="transfer failed" err="cannot find ingester to transfer chunks to: no pending ingesters"
level=error ts=2020-12-09T15:11:15.648001268Z caller=transfer.go:200 msg="transfer failed" err="cannot find ingester to transfer chunks to: no pending ingesters"
level=error ts=2020-12-09T15:11:19.15412144Z caller=transfer.go:200 msg="transfer failed" err="cannot find ingester to transfer chunks to: no pending ingesters"
level=error ts=2020-12-09T15:11:22.501136562Z caller=transfer.go:200 msg="transfer failed" err="cannot find ingester to transfer chunks to: no pending ingesters"
level=error ts=2020-12-09T15:11:22.501187998Z caller=lifecycler.go:788 msg="failed to transfer chunks to another instance" ring=ingester err="terminated after 10 retries"
```
CC @sreis is that maybe https://github.com/opstrace/opstrace/issues/144?

**Comment by sreis** [comment]
@jgehrcke Yes! Not sure why it never recovered the deployment though. Mind testing #145 in this branch?

**Comment by jgehrcke** [comment]
> @jgehrcke Yes! Not sure why it never recovered the deployment though. Mind testing #145 in this branch?

Thanks! Let's wait for the current CI run in #145 to complete and just merge it if green -- then I'll rebase :).

**Comment by jgehrcke** [comment]
Landed https://github.com/opstrace/opstrace/pull/145 (thanks, @sreis!), rebased on latest `main`, force-pushed. Let's see.

**Comment by jgehrcke** [comment]
Lovely. Got super far already. Cluster creation passed, test-remote passed, looker tests passed. CLI's `list` tests fail:
```
[2020-12-09T16:15:16Z] + source ci/test-cli/cli-tests-with-cluster.sh
[2020-12-09T16:15:16Z] ++ export GOOGLE_APPLICATION_CREDENTIALS=./secrets/gcp-credentials.json
[2020-12-09T16:15:16Z] ++ GOOGLE_APPLICATION_CREDENTIALS=./secrets/gcp-credentials.json
[2020-12-09T16:15:16Z] ++ test_list
[2020-12-09T16:15:16Z] ++ set -o xtrace
[2020-12-09T16:15:16Z] ++ ./build/bin/opstrace list gcp --log-level=debug
[2020-12-09T16:15:17Z] 2020-12-09T16:15:17.922Z info: logging to file: opstrace_cli_list_20201209-161517Z.log
[2020-12-09T16:15:17Z] 2020-12-09T16:15:17.922Z debug: cli args:
[2020-12-09T16:15:17Z] {
[2020-12-09T16:15:17Z]   "showVersion": false,
[2020-12-09T16:15:17Z]   "command": "list",
[2020-12-09T16:15:17Z]   "logLevel": "debug",
[2020-12-09T16:15:17Z]   "cloudProvider": "gcp"
[2020-12-09T16:15:17Z] }
[2020-12-09T16:15:17Z] 2020-12-09T16:15:17.923Z debug: CLI build information: {
[2020-12-09T16:15:17Z]   "BRANCH_NAME": "jp/gcp-ci-shards",
[2020-12-09T16:15:17Z]   "VERSION_STRING": "eddfaf65-ci",
[2020-12-09T16:15:17Z]   "COMMIT": "eddfaf6",
[2020-12-09T16:15:17Z]   "BUILD_TIME_RFC3339": "2020-12-09 15:50:12+00:00",
[2020-12-09T16:15:17Z]   "BUILD_HOSTNAME": "4ca53c9c32fa"
[2020-12-09T16:15:17Z] }
[2020-12-09T16:15:17Z] 2020-12-09T16:15:17.969Z debug: GCP project ID: vast-pad-240918
[2020-12-09T16:15:18Z] bk-1335-3f6-g
[2020-12-09T16:15:18Z] bk-3162-180-g
[2020-12-09T16:15:18Z] matdev
[2020-12-09T16:15:18Z] 2020-12-09T16:15:18.431Z debug: shut down logger, then exit with code 0
[2020-12-09T16:15:18Z] ++ ./build/bin/opstrace list gcp
[2020-12-09T16:15:18Z] ++ grep bk-3231-edd-g
[2020-12-09T16:15:19Z] 2020-12-09T16:15:19.557Z info: logging to file: opstrace_cli_list_20201209-161519Z.log
[2020-12-09T16:15:20Z] + teardown
[2020-12-09T16:15:20Z] + LAST_EXITCODE_BEFORE_TEARDOWN=1
[2020-12-09T16:15:20Z] + echo '+++ Exit status before entering teardown(): 1'
```
GCP project ID seems to still be hard-coded somewhere, looking.

**Comment by jgehrcke** [comment]
`shuf` from coreutils, checking balance:

```
$ for lol in $(seq 1000); do shuf -n1 -e a b c; done > shufdata
$ less shufdata | sort | uniq -c
    350 a
    316 b
    334 c
```
and with a larger sample size:
```
$ for lol in $(seq 10000); do shuf -n1 -e a b c; done > shufdata
$ less shufdata | sort | uniq -c
   3315 a
   3377 b
   3308 c
```
Looks good.

**Pull request merged**
