### PR TITLE
test-remote: cover tenant creation flow, authn token usage derived from custom key pair (WIP, part 2)

### PR DESCRIPTION
**Pull request by jgehrcke**

### CODE REVIEW

**Comment by jgehrcke** [comment]
In the last CI run, the tenant's API did not become available in within 30 minutes. DNS resolution kept failing during that time. In 'local' tests, the tenant API became available within 15 minutes. The decisive difference? Not sure yet.

A bad tenant name? Therefore: https://github.com/opstrace/opstrace/issues/710

**Comment by jgehrcke** [comment]
okay, need to see tomorrow what went wrong -- by going through authenticator logs.

**Comment by jgehrcke** [comment]
I went through the BK artifacts to look into the Cortex API logs which contain the authenticator logs. Both Cortex API pods picked up the public key with ID `ca8e120257c4b84f08ae024db6522488c21f5033`:

```
time="2021-05-11T14:48:20Z" level=info msg="cortex querier URL: http://query-frontend.cortex.svc.cluster.local"
time="2021-05-11T14:48:20Z" level=info msg="cortex distributor URL: http://distributor.cortex.svc.cluster.local"
time="2021-05-11T14:48:20Z" level=info msg="listen address: :8080"
time="2021-05-11T14:48:20Z" level=info msg="tenant name: default"
time="2021-05-11T14:48:20Z" level=info msg="API authentication enabled: true"
time="2021-05-11T14:48:20Z" level=info msg="API_AUTHTOKEN_VERIFICATION_PUBKEY is not set, don't use fallback key"
time="2021-05-11T14:48:20Z" level=info msg="API_AUTHTOKEN_VERIFICATION_PUBKEY_SET value: {\"98cb36b08cfe19ffd1ac9538c10eac300665ca39\":\"-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz4N+XGrbdHV2hU02kTO8\\n/y06r3tnHkzJb6rnO6nPIup7r4u9XSXtzKTVXYrysI0fmkTDC5FIioP9qlx0BYbs\\nGwu51PwpkQkXeZh34cjzyOBJ/UHeZ0arLCVOohCHWjuIEkVmryC9iqd3GUy8yxAH\\n+MUXmr7hBx5c/xFc5e3YBW8pu6RhMWbJeQ/lc16O7OJbpVaPRcNC/oVECj8VI1vb\\nWn4xDL8EQOzCm+DSp+C9NmJ6NQFS+Kho68zREmKVWJTzAXS8jW8iu7kmqjXp4TXs\\nfy0vNt69KEwuXjykzsLJ4vuFEfYlgHfqyviFV69znSlDsprAy8710z3qikNVuShw\\nLwIDAQAB\\n-----END PUBLIC KEY-----\\n\",\"ca8e120257c4b84f08ae024db6522488c21f5033\":\"-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlzRegx0GzIzFkvgaYj3U\\nTmH5oxWC3rT1zsdyZtKjIgfy85yUQwUhdM+YixWhJaPeggbmIvckl6X1E05CdPGx\\nJLZqL8OsrcX0VoQRg4R0OStFJp4tO2pwSo7LlaHpXPoTNGyLxvyWBrXFPz0ELpZW\\n5ykHkmZmRWxLEKygJLGqmxsMI/hKTZt6pny9afiwHnjaCTSuIkpyBEphPgnaJEyJ\\nDCxvRU1IKGn+/5Pr1KAMQ05csmm0uwlwkatnut3QVOc+WgjmoN9ESbAD+7uge8bu\\nndB+blEwLc1uKMvrLpiJUiOhwIpCfdtyjP8k/7wq8SGamW6wVtgrkyZPuTDa3eNF\\npQIDAQAB\\n-----END PUBLIC KEY-----\\n\"}"
time="2021-05-11T14:48:20Z" level=info msg="parse PEM bytes for key with ID 98cb36b08cfe19ffd1ac9538c10eac300665ca39"
time="2021-05-11T14:48:20Z" level=info msg="Deserialized RSA public key with modulus size: 2048 bits"
time="2021-05-11T14:48:20Z" level=info msg="calculated key ID from PEM data: 98cb36b08cfe19ffd1ac9538c10eac300665ca39"
time="2021-05-11T14:48:20Z" level=info msg="key ID confirmed"
time="2021-05-11T14:48:20Z" level=info msg="Parsed RSA public key. Modulus size: 2048 bits"
time="2021-05-11T14:48:20Z" level=info msg="parse PEM bytes for key with ID ca8e120257c4b84f08ae024db6522488c21f5033"
time="2021-05-11T14:48:20Z" level=info msg="Deserialized RSA public key with modulus size: 2048 bits"
time="2021-05-11T14:48:20Z" level=info msg="calculated key ID from PEM data: ca8e120257c4b84f08ae024db6522488c21f5033"
time="2021-05-11T14:48:20Z" level=info msg="key ID confirmed"
time="2021-05-11T14:48:20Z" level=info msg="Parsed RSA public key. Modulus size: 2048 bits"
```

**Comment by jgehrcke** [comment]
## Was the authenticator configured with the relevant pub key?

I went through the BK artifacts to look into the Cortex API logs which contain the authenticator logs. Both Cortex API pods picked up the public key with ID `ca8e120257c4b84f08ae024db6522488c21f5033`:

Yes.

```
time="2021-05-11T14:48:20Z" level=info msg="cortex querier URL: http://query-frontend.cortex.svc.cluster.local"
time="2021-05-11T14:48:20Z" level=info msg="cortex distributor URL: http://distributor.cortex.svc.cluster.local"
time="2021-05-11T14:48:20Z" level=info msg="listen address: :8080"
time="2021-05-11T14:48:20Z" level=info msg="tenant name: default"
time="2021-05-11T14:48:20Z" level=info msg="API authentication enabled: true"
time="2021-05-11T14:48:20Z" level=info msg="API_AUTHTOKEN_VERIFICATION_PUBKEY is not set, don't use fallback key"
time="2021-05-11T14:48:20Z" level=info msg="API_AUTHTOKEN_VERIFICATION_PUBKEY_SET value: {\"98cb36b08cfe19ffd1ac9538c10eac300665ca39\":\"-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz4N+XGrbdHV2hU02kTO8\\n/y06r3tnHkzJb6rnO6nPIup7r4u9XSXtzKTVXYrysI0fmkTDC5FIioP9qlx0BYbs\\nGwu51PwpkQkXeZh34cjzyOBJ/UHeZ0arLCVOohCHWjuIEkVmryC9iqd3GUy8yxAH\\n+MUXmr7hBx5c/xFc5e3YBW8pu6RhMWbJeQ/lc16O7OJbpVaPRcNC/oVECj8VI1vb\\nWn4xDL8EQOzCm+DSp+C9NmJ6NQFS+Kho68zREmKVWJTzAXS8jW8iu7kmqjXp4TXs\\nfy0vNt69KEwuXjykzsLJ4vuFEfYlgHfqyviFV69znSlDsprAy8710z3qikNVuShw\\nLwIDAQAB\\n-----END PUBLIC KEY-----\\n\",\"ca8e120257c4b84f08ae024db6522488c21f5033\":\"-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlzRegx0GzIzFkvgaYj3U\\nTmH5oxWC3rT1zsdyZtKjIgfy85yUQwUhdM+YixWhJaPeggbmIvckl6X1E05CdPGx\\nJLZqL8OsrcX0VoQRg4R0OStFJp4tO2pwSo7LlaHpXPoTNGyLxvyWBrXFPz0ELpZW\\n5ykHkmZmRWxLEKygJLGqmxsMI/hKTZt6pny9afiwHnjaCTSuIkpyBEphPgnaJEyJ\\nDCxvRU1IKGn+/5Pr1KAMQ05csmm0uwlwkatnut3QVOc+WgjmoN9ESbAD+7uge8bu\\nndB+blEwLc1uKMvrLpiJUiOhwIpCfdtyjP8k/7wq8SGamW6wVtgrkyZPuTDa3eNF\\npQIDAQAB\\n-----END PUBLIC KEY-----\\n\"}"
time="2021-05-11T14:48:20Z" level=info msg="parse PEM bytes for key with ID 98cb36b08cfe19ffd1ac9538c10eac300665ca39"
time="2021-05-11T14:48:20Z" level=info msg="Deserialized RSA public key with modulus size: 2048 bits"
time="2021-05-11T14:48:20Z" level=info msg="calculated key ID from PEM data: 98cb36b08cfe19ffd1ac9538c10eac300665ca39"
time="2021-05-11T14:48:20Z" level=info msg="key ID confirmed"
time="2021-05-11T14:48:20Z" level=info msg="Parsed RSA public key. Modulus size: 2048 bits"
time="2021-05-11T14:48:20Z" level=info msg="parse PEM bytes for key with ID ca8e120257c4b84f08ae024db6522488c21f5033"
time="2021-05-11T14:48:20Z" level=info msg="Deserialized RSA public key with modulus size: 2048 bits"
time="2021-05-11T14:48:20Z" level=info msg="calculated key ID from PEM data: ca8e120257c4b84f08ae024db6522488c21f5033"
time="2021-05-11T14:48:20Z" level=info msg="key ID confirmed"
time="2021-05-11T14:48:20Z" level=info msg="Parsed RSA public key. Modulus size: 2048 bits"
```

## Is the token used by CI 'good'?

Seemingly, yes:

Screenshot from 2021-05-12 11-51-08

**Comment by jgehrcke** [comment]
Shoot, the authenticator log above is for the `default` tenant. That's rather useless. The Cortex API proxy is deployed on a per-tenant basis, and therefore I need to inspect different logs. Using the collection cluster to dig that up, query for `{opstrace_cluster_name="prs-bk-4147-5bc-g", k8s_namespace_name="testtenant-hewojh-tenant"}`.

**Comment by jgehrcke** [comment]
Refined query:
```
{opstrace_cluster_name="prs-bk-4147-5bc-g", k8s_namespace_name="testtenant-hewojh-tenant", k8s_container_name="cortex-api"}
```

Digging. Decisive part:

```
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="Parsed RSA public key. Modulus size: 2048 bits"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="cortex querier URL: http://query-frontend.cortex.svc.cluster.local"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="cortex distributor URL: http://distributor.cortex.svc.cluster.local"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="listen address: :8080"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="tenant name: testtenant-hewojh"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="API authentication enabled: true"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="API_AUTHTOKEN_VERIFICATION_PUBKEY is not set, don't use fallback key"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="API_AUTHTOKEN_VERIFICATION_PUBKEY_SET value: {\"98cb36b08cfe19ffd1ac9538c10eac300665ca39\":\"-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz4N+XGrbdHV2hU02kTO8\\n/y06r3tnHkzJb6rnO6nPIup7r4u9XSXtzKTVXYrysI0fmkTDC5FIioP9qlx0BYbs\\nGwu51PwpkQkXeZh34cjzyOBJ/UHeZ0arLCVOohCHWjuIEkVmryC9iqd3GUy8yxAH\\n+MUXmr7hBx5c/xFc5e3YBW8pu6RhMWbJeQ/lc16O7OJbpVaPRcNC/oVECj8VI1vb\\nWn4xDL8EQOzCm+DSp+C9NmJ6NQFS+Kho68zREmKVWJTzAXS8jW8iu7kmqjXp4TXs\\nfy0vNt69KEwuXjykzsLJ4vuFEfYlgHfqyviFV69znSlDsprAy8710z3qikNVuShw\\nLwIDAQAB\\n-----END PUBLIC KEY-----\\n\",\"ca8e120257c4b84f08ae024db6522488c21f5033\":\"-----BEGIN PUBLIC KEY-----\\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlzRegx0GzIzFkvgaYj3U\\nTmH5oxWC3rT1zsdyZtKjIgfy85yUQwUhdM+YixWhJaPeggbmIvckl6X1E05CdPGx\\nJLZqL8OsrcX0VoQRg4R0OStFJp4tO2pwSo7LlaHpXPoTNGyLxvyWBrXFPz0ELpZW\\n5ykHkmZmRWxLEKygJLGqmxsMI/hKTZt6pny9afiwHnjaCTSuIkpyBEphPgnaJEyJ\\nDCxvRU1IKGn+/5Pr1KAMQ05csmm0uwlwkatnut3QVOc+WgjmoN9ESbAD+7uge8bu\\nndB+blEwLc1uKMvrLpiJUiOhwIpCfdtyjP8k/7wq8SGamW6wVtgrkyZPuTDa3eNF\\npQIDAQAB\\n-----END PUBLIC KEY-----\\n\"}"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="parse PEM bytes for key with ID ca8e120257c4b84f08ae024db6522488c21f5033"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="Deserialized RSA public key with modulus size: 2048 bits"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="calculated key ID from PEM data: ca8e120257c4b84f08ae024db6522488c21f5033"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="key ID confirmed"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="Parsed RSA public key. Modulus size: 2048 bits"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="parse PEM bytes for key with ID 98cb36b08cfe19ffd1ac9538c10eac300665ca39"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="Deserialized RSA public key with modulus size: 2048 bits"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="calculated key ID from PEM data: 98cb36b08cfe19ffd1ac9538c10eac300665ca39"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="key ID confirmed"
2021-05-11 17:07:25	
time="2021-05-11T15:07:25Z" level=info msg="Parsed RSA public key. Modulus size: 2048 bits"
2021-05-11 17:11:16	
time="2021-05-11T15:11:16Z" level=info msg="invalid subject (tenant- prefix missing)"
2021-05-11 17:11:16	
time="2021-05-11T15:11:16Z" level=info msg="emit 401. Err: bad authentication token"
```

- First of all, it picked up the public key with ID ca8e120257c4b84f08ae024db6522488c21f5033.
- And it logs what's wrong with the authentication token (I've rightfully decided to put that detail only in the authenticator log, not into the error message seen by the client).

Let's see:
```
time="2021-05-11T15:11:16Z" level=info msg="invalid subject (tenant- prefix missing)"
2021-05-11 17:11:16	
time="2021-05-11T15:11:16Z" level=info msg="emit 401. Err: bad authentication token"
```

Compare that to the timestamp of 
```
[2021-05-11T15:11:16Z] 2021-05-11T15:11:16.631Z �[32minfo�[39m: HTTP resp to GET(https://cortex.testtenant-hewojh.prs-bk-4147-5bc-g.opstrace.io/api/v1/labels):
[2021-05-11T15:11:16Z]   status: 401
```

Direct correspondence.

So. The authenticator code claims `"invalid subject (tenant- prefix missing)"`. But when we inspect the token, that is not quite true:

```
{
  "iat": 1620744480,
  "exp": 1936320480,
  "aud": "opstrace-cluster-prs-bk-4147-5bc-g",
  "iss": "opstrace-cli",
  "sub": "tenant-testtenant-hewojh"
}
```

What this pinpoints, though, is that the authenticator does _not_ seem to see the token in the exact same way  as we've logged it in CI. There might be a whitespace mess-up somewhere. I did watch out for that before, but will have a closer look. Also, the authenticator-generated error message might be misleading: what if `"invalid subject (tenant- prefix missing)"` actually means that the payload could not be parsed? Will double-check that, too.

**Comment by jgehrcke** [comment]
Okay, that is fun. A legit authenticator bug. I did not plan for tenant names to contain dashes:

```
	// Custom convention: encode Opstrace tenant name in subject, expect
	// a specific prefix.
	ssplits := strings.Split(claims.Subject, "tenant-")
	if len(ssplits) != 2 {
		log.Infof("invalid subject (tenant- prefix missing)")
		return "", fmt.Errorf("bad authentication token")
	}
```

([code](https://github.com/opstrace/opstrace/blob/786f2e79a3f374d4cf771c211630530732ce40ae/go/pkg/authenticator/jwt.go#L61))

For the tenant name `tenant-testtenant-hewojh`, `len(ssplits)` is 3 :see_no_evil:

**Comment by jgehrcke** [comment]
Finally. Merging.

**Comment by MatApple** [comment]
Very nice to follow your journey of commits! Nicely documented. Glad to have a default logger since it's caught me out a few times too.

@terrcin As we move forward with UI we should replace axios with the http client @jgehrcke has been iterating on in our Utils package.

**Pull request merged**
