### PR TITLE
cli(upgrades): fix invalid instance dns name

### PR DESCRIPTION
**Pull request by sreis**
From a recent upgrades pipeline [build](https://buildkite.com/opstrace/upgrade-tests/builds/953#8d5e2359-b655-4505-97a0-87c0f4f45610/2115-3404)

```
[2021-07-09T12:45:18Z] 2021-07-09T12:45:18.838Z debug: https://cortex.default.upgrade-bk-953-29b-g/api/v1/labels: HTTP request failed with: getaddrinfo ENOTFOUND cortex.default.upgrade-bk-953-29b-g
```

It's missing the `opstrace.io` domain.

### CODE REVIEW

**Comment by jgehrcke** [comment]
And again, sorry for the hassle :).

Should we try to make CI cover this a little better in regular PR CI?

**Comment by sreis** [comment]
> Should we try to make CI cover this a little better in regular PR CI?

Any suggestions apart from running the upgrades pipeline on every PR?

**Comment by jgehrcke** [comment]
> Any suggestions apart from running the upgrades pipeline on every PR?

Some kind of smoke test which would initiate the upgrade code path, but back out before actually doing the bulk of the work maybe? Would have caught this here, and also https://github.com/opstrace/opstrace/pull/1014 I think.

we could add an undocumented command line switch to the upgrade command for it to back out. Did this for the `crashtest`, too :D https://github.com/opstrace/opstrace/blob/29bb931b2ff765b445ce0632d1d76f0971e6879e/packages/cli/src/index.ts#L159

**Comment by sreis** [comment]
> Some kind of test which would exercise the upgrade code path in the CLI, but back out before actually doing the bulk of the work maybe? Would have caught this here, and also #1014 I think.

Well, I'm up for anything at this point really but it would be better to make testing upgrades a first-class citizen without impacting dev velocity and CI budget.

**Comment by sreis** [comment]
Add a dry run test with commit https://github.com/opstrace/opstrace/pull/1022/commits/06c689471c1d669e9eb08cc8e2fe87f4ff50854a.

**Pull request merged**
