### PR TITLE
bump: upgrade sentry from 5.27.3 to 6.2.5

### PR DESCRIPTION
**Pull request by triclambert**
On the web dashboard, I noticed that there was a newer version.

### CODE REVIEW

**Comment by terrcin** [comment]
that's quite the version bump. whats changed? anything breaking between v5 and v6?

**Comment by triclambert** [comment]
No breaking changes in v6, as noted here:  https://github.com/getsentry/sentry-javascript/releases/tag/6.0.0

**Comment by terrcin** [comment]
@triclambert I've updated the `yarn.lock` then tested it out in dev mode, in that I made sure the UI ran as expected. Not tested anything else. Seems fine to me.

**Comment by triclambert** [comment]
Great, thanks.  Since you're comfortable with it I'll go ahead and merge it.

**Pull request merged**
